name: Build with make

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc]    

    steps:
    - uses: actions/checkout@v2
    - name: build c2man
      run: ./build.sh build_linux

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        path: fribidi-*.tar.xz
        name: fribidi-libs

    - name: 'Upload build logs'
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        path: test/test-suite.log
