name: Build with make for linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc]    

    steps:
    - uses: actions/checkout@v2
    - name: build fribidi libs
      run: mkdir ./build_linux && ./build.sh ${{ github.workspace }}/build_linux && ls -lh ${{ github.workspace }}/build_linux && echo "working-directory = ",${{ github.workspace }}
      working-directory: ${{ github.workspace }}
    - name: zip libs
      run: zip -r fribidi-libs-for-linux.zip ${{ github.workspace }}/build_linux
      working-directory: ${{ github.workspace }}

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        path: fribidi-libs-for-linux.zip
        name: fribidi-libs-for-linux

    - name: 'Upload build logs'
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        path: test/test-suite.log
